FROM docker.io/library/debian:bookworm-slim

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      binutils-arm-linux-gnueabi \
      gcc-12-arm-linux-gnueabi \
      libc6-dev-armel-cross \
      make \
      python3 \
 && ln -s /usr/bin/arm-linux-gnueabi-gcc-12 \
      /usr/local/bin/arm-linux-gnueabi-gcc \
 && rm -rf /var/lib/apt/lists/*
