#!/usr/bin/env bash
set -euo pipefail

project_root=$(cd "$(dirname "$0")/.." && pwd)
idf_path="$project_root/.esp-idf"
tools_path="$project_root/.idf_tools"
idf_version=v6.1

if [[ ! -d "$idf_path/.git" ]]; then
  git clone --recursive --depth 1 --shallow-submodules \
    --branch "$idf_version" https://github.com/espressif/esp-idf.git "$idf_path"
fi

IDF_TOOLS_PATH="$tools_path" "$idf_path/install.sh" esp32s3
