# SPDX-License-Identifier: MPL-2.0
FROM docker.io/library/debian:bookworm-slim

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      binutils-arm-linux-gnueabi \
      bison \
      build-essential \
      flex \
      gcc-12-arm-linux-gnueabi \
      libc6-dev-armel-cross \
      pkg-config \
 && ln -s /usr/bin/arm-linux-gnueabi-gcc-12 /usr/local/bin/arm-linux-gnueabi-gcc \
 && rm -rf /var/lib/apt/lists/*
