#pragma once

#define RX3_S3_CONFIG_ETHERTYPE 0x88b5
#define RX3_S3_CONFIG_HEADER_SIZE 10
#define RX3_S3_CONFIG_SSID_MAX_LENGTH 32
#define RX3_S3_CONFIG_PASSWORD_MAX_LENGTH 63
#define RX3_S3_CONFIG_STATUS_FIXED_SIZE 9
#define RX3_S3_CONFIG_RESPONSE_BIT 0x80

typedef enum {
    RX3_S3_CONFIG_GET_STATUS = 1,
    RX3_S3_CONFIG_SET_CREDENTIALS = 2,
    RX3_S3_CONFIG_RECONNECT = 3,
} rx3_s3_config_opcode_t;

typedef enum {
    RX3_S3_CONFIG_OK = 0,
    RX3_S3_CONFIG_BAD_REQUEST = 1,
    RX3_S3_CONFIG_FAILED = 2,
} rx3_s3_config_status_code_t;

enum {
    RX3_S3_CONFIG_FLAG_WIFI_CONNECTED = 1U << 0,
    RX3_S3_CONFIG_FLAG_PASSWORD_SET = 1U << 1,
};
