#!/usr/bin/env python3
"""Generate the dependency-free C constants shared with the RX3 module."""

from __future__ import annotations

from pathlib import Path
import re
import zlib

from .controls import CATALOG, CATALOG_PATH, CONTROLS


OUTPUT = Path(__file__).with_name("rx3_remote_protocol.h")


def macro_name(name: str) -> str:
    return re.sub(r"[^A-Z0-9]+", "_", name.upper()).strip("_")


def render() -> str:
    crc32 = zlib.crc32(CATALOG_PATH.read_bytes())
    controls = "\n".join(
        f"#define RX3R_CONTROL_{macro_name(control.name)} 0x{control.key_code:04x}u"
        for control in CONTROLS
    )
    return f"""/* SPDX-License-Identifier: MPL-2.0
 * Generated by python -m tools.rx3_remote.generate_header. Do not edit.
 */
#ifndef RX3_REMOTE_PROTOCOL_H
#define RX3_REMOTE_PROTOCOL_H

#define RX3R_VERSION 1u
#define RX3R_PORT 7357u
#define RX3R_MAX_PAYLOAD 4096u
#define RX3R_SCHEMA_REVISION {CATALOG['revision']}u
#define RX3R_SCHEMA_CRC32 0x{crc32:08x}u
#define RX3R_CONTROL_COUNT {len(CONTROLS)}u

#define RX3R_HELLO 1u
#define RX3R_SCHEMA 2u
#define RX3R_SUBSCRIBE 3u
#define RX3R_EVENT 4u
#define RX3R_COMMAND 5u
#define RX3R_ACK 6u
#define RX3R_ERROR 7u
#define RX3R_PING 8u
#define RX3R_PONG 9u

#define RX3R_CAP_EVENTS (1u << 0)
#define RX3R_CAP_COMMANDS (1u << 1)
#define RX3R_CAP_SCHEMA (1u << 2)
#define RX3R_EVENT_CONTROLS (1u << 0)
#define RX3R_SOURCE_PHYSICAL 1u
#define RX3R_SOURCE_REMOTE 2u

#define RX3R_OP_PRESSED 0u
#define RX3R_OP_LONG_PRESSED 1u
#define RX3R_OP_RELEASED 2u
#define RX3R_OP_RELEASED_AFTER_LONG_PRESS 3u
#define RX3R_OP_RELATIVE_MOVED 4u
#define RX3R_OP_ABSOLUTE_MOVED 5u
#define RX3R_OP_VALUE_CHANGED 6u

#define RX3R_ERROR_INVALID_MESSAGE 1u
#define RX3R_ERROR_INVALID_COMMAND 2u
#define RX3R_ERROR_UNSUPPORTED_CONTROL 3u
#define RX3R_ERROR_BUSY 4u
#define RX3R_ERROR_INTERNAL 5u

/* Multi-byte fields are network byte order. These byte-array layouts avoid
 * alignment assumptions in the preloaded ARMv7 module. */
struct rx3r_header {{
    unsigned char magic[4];
    unsigned char version;
    unsigned char type;
    unsigned char flags_be[2];
    unsigned char request_id_be[4];
    unsigned char payload_length_be[4];
}};

struct rx3r_hello {{
    unsigned char rbp_build_prefix[4];
    unsigned char firmware_major_be[2];
    unsigned char firmware_minor_be[2];
    unsigned char schema_revision_be[4];
    unsigned char capabilities_be[4];
}};

struct rx3r_control {{
    unsigned char key_code_be[2];
    unsigned char operation;
    unsigned char channel;
    unsigned char value_be[4];
    unsigned char float_bits_be[4];
    unsigned char auxiliary_be[4];
}};

struct rx3r_control_event {{
    struct rx3r_control control;
    unsigned char source;
    unsigned char flags;
    unsigned char reserved[2];
    unsigned char timestamp_us_be[8];
}};

struct rx3r_schema {{
    unsigned char crc32_be[4];
    unsigned char control_count_be[4];
}};

struct rx3r_subscription {{
    unsigned char event_mask_be[4];
}};

struct rx3r_result {{
    unsigned char result_be[4];
}};

struct rx3r_error {{
    unsigned char code_be[4];
    unsigned char detail_be[4];
}};

{controls}

#endif
"""


def main() -> None:
    OUTPUT.write_text(render())


if __name__ == "__main__":
    main()
