/* SPDX-License-Identifier: MPL-2.0
 * Generated by python -m tools.rx3_remote.generate_header. Do not edit.
 */
#ifndef RX3_REMOTE_PROTOCOL_H
#define RX3_REMOTE_PROTOCOL_H

#define RX3R_VERSION 1u
#define RX3R_PORT 7357u
#define RX3R_MAX_PAYLOAD 4096u
#define RX3R_SCHEMA_REVISION 1u
#define RX3R_SCHEMA_CRC32 0x4257e3cbu
#define RX3R_CONTROL_COUNT 89u

#define RX3R_HELLO 1u
#define RX3R_SCHEMA 2u
#define RX3R_SUBSCRIBE 3u
#define RX3R_EVENT 4u
#define RX3R_COMMAND 5u
#define RX3R_ACK 6u
#define RX3R_ERROR 7u
#define RX3R_PING 8u
#define RX3R_PONG 9u

#define RX3R_CAP_EVENTS (1u << 0)
#define RX3R_CAP_COMMANDS (1u << 1)
#define RX3R_CAP_SCHEMA (1u << 2)
#define RX3R_EVENT_CONTROLS (1u << 0)
#define RX3R_SOURCE_PHYSICAL 1u
#define RX3R_SOURCE_REMOTE 2u

#define RX3R_OP_PRESSED 0u
#define RX3R_OP_LONG_PRESSED 1u
#define RX3R_OP_RELEASED 2u
#define RX3R_OP_RELEASED_AFTER_LONG_PRESS 3u
#define RX3R_OP_RELATIVE_MOVED 4u
#define RX3R_OP_ABSOLUTE_MOVED 5u
#define RX3R_OP_VALUE_CHANGED 6u

#define RX3R_ERROR_INVALID_MESSAGE 1u
#define RX3R_ERROR_INVALID_COMMAND 2u
#define RX3R_ERROR_UNSUPPORTED_CONTROL 3u
#define RX3R_ERROR_BUSY 4u
#define RX3R_ERROR_INTERNAL 5u

/* Multi-byte fields are network byte order. These byte-array layouts avoid
 * alignment assumptions in the preloaded ARMv7 module. */
struct rx3r_header {
    unsigned char magic[4];
    unsigned char version;
    unsigned char type;
    unsigned char flags_be[2];
    unsigned char request_id_be[4];
    unsigned char payload_length_be[4];
};

struct rx3r_hello {
    unsigned char rbp_build_prefix[4];
    unsigned char firmware_major_be[2];
    unsigned char firmware_minor_be[2];
    unsigned char schema_revision_be[4];
    unsigned char capabilities_be[4];
};

struct rx3r_control {
    unsigned char key_code_be[2];
    unsigned char operation;
    unsigned char channel;
    unsigned char value_be[4];
    unsigned char float_bits_be[4];
    unsigned char auxiliary_be[4];
};

struct rx3r_control_event {
    struct rx3r_control control;
    unsigned char source;
    unsigned char flags;
    unsigned char reserved[2];
    unsigned char timestamp_us_be[8];
};

struct rx3r_schema {
    unsigned char crc32_be[4];
    unsigned char control_count_be[4];
};

struct rx3r_subscription {
    unsigned char event_mask_be[4];
};

struct rx3r_result {
    unsigned char result_be[4];
};

struct rx3r_error {
    unsigned char code_be[4];
    unsigned char detail_be[4];
};

#define RX3R_CONTROL_BROWSER_SOURCE 0x0201u
#define RX3R_CONTROL_BROWSER_BROWSE 0x0202u
#define RX3R_CONTROL_RECORDER_USB_RECORD 0x0401u
#define RX3R_CONTROL_RECORDER_TRACK_MARK 0x0402u
#define RX3R_CONTROL_BEAT_FX_QUANTIZE 0x0493u
#define RX3R_CONTROL_MIC_SWITCH 0x0814u
#define RX3R_CONTROL_MIC_EQ_HIGH 0x0815u
#define RX3R_CONTROL_MIC_EQ_LOW 0x0816u
#define RX3R_CONTROL_DECK_PLAY_PAUSE 0x4101u
#define RX3R_CONTROL_DECK_CUE 0x4102u
#define RX3R_CONTROL_DECK_SHIFT 0x4103u
#define RX3R_CONTROL_DECK_VINYL_MODE 0x4104u
#define RX3R_CONTROL_DECK_TEMPO_RANGE 0x4107u
#define RX3R_CONTROL_DECK_MASTER_TEMPO 0x4108u
#define RX3R_CONTROL_DECK_TEMPO_SLIDER 0x4109u
#define RX3R_CONTROL_DECK_TIME_MODE_AUTO_CUE 0x410au
#define RX3R_CONTROL_DECK_QUANTIZE 0x410bu
#define RX3R_CONTROL_DECK_LOOP_IN 0x410cu
#define RX3R_CONTROL_DECK_LOOP_OUT 0x410du
#define RX3R_CONTROL_DECK_RELOOP_EXIT 0x410eu
#define RX3R_CONTROL_DECK_REVERSE 0x410fu
#define RX3R_CONTROL_DECK_SLIP 0x4110u
#define RX3R_CONTROL_DECK_MASTER 0x4111u
#define RX3R_CONTROL_DECK_SYNC 0x4112u
#define RX3R_CONTROL_DECK_HOT_CUE_MODE 0x4113u
#define RX3R_CONTROL_DECK_AUTO_BEAT_LOOP 0x4114u
#define RX3R_CONTROL_DECK_SLIP_LOOP_MODE 0x4115u
#define RX3R_CONTROL_DECK_BEAT_JUMP 0x4116u
#define RX3R_CONTROL_DECK_PAD_1 0x4117u
#define RX3R_CONTROL_DECK_PAD_2 0x4118u
#define RX3R_CONTROL_DECK_PAD_3 0x4119u
#define RX3R_CONTROL_DECK_PAD_4 0x411au
#define RX3R_CONTROL_DECK_PAD_5 0x411bu
#define RX3R_CONTROL_DECK_PAD_6 0x411cu
#define RX3R_CONTROL_DECK_PAD_7 0x411du
#define RX3R_CONTROL_DECK_PAD_8 0x411eu
#define RX3R_CONTROL_DECK_SEARCH_FORWARD 0x411fu
#define RX3R_CONTROL_DECK_SEARCH_REVERSE 0x4120u
#define RX3R_CONTROL_DECK_VINYL_SPEED_ADJUST 0x4121u
#define RX3R_CONTROL_DECK_CUE_DELETE 0x4124u
#define RX3R_CONTROL_DECK_CUE_MEMORY 0x4125u
#define RX3R_CONTROL_DECK_NEEDLE_SEARCH 0x4126u
#define RX3R_CONTROL_BROWSER_ROTARY_SELECTOR 0x420cu
#define RX3R_CONTROL_BROWSER_BACK 0x420du
#define RX3R_CONTROL_BROWSER_TAG_TRACK 0x420eu
#define RX3R_CONTROL_BROWSER_TRACK_FILTER 0x420fu
#define RX3R_CONTROL_BROWSER_DECK_SELECT 0x4212u
#define RX3R_CONTROL_BROWSER_TRACK_FORWARD 0x4214u
#define RX3R_CONTROL_BROWSER_TRACK_REVERSE 0x4215u
#define RX3R_CONTROL_DECK_JOG 0x4305u
#define RX3R_CONTROL_DECK_JOG_TOUCH 0x4306u
#define RX3R_CONTROL_BROWSER_LOAD 0x4311u
#define RX3R_CONTROL_DECK_CALL_NEXT 0x4322u
#define RX3R_CONTROL_DECK_CALL_PREVIOUS 0x4323u
#define RX3R_CONTROL_MASTER_LEVEL 0x4403u
#define RX3R_CONTROL_BOOTH_LEVEL 0x4404u
#define RX3R_CONTROL_HEADPHONES_MIX 0x4405u
#define RX3R_CONTROL_HEADPHONES_LEVEL 0x4406u
#define RX3R_CONTROL_MASTER_CUE 0x4407u
#define RX3R_CONTROL_LINK_CUE 0x4408u
#define RX3R_CONTROL_AUX_GAIN 0x4409u
#define RX3R_CONTROL_AUX_LEVEL 0x440au
#define RX3R_CONTROL_BEAT_FX_SWITCH 0x448bu
#define RX3R_CONTROL_BEAT_FX_CHANNEL 0x448cu
#define RX3R_CONTROL_BEAT_FX_ON_OFF 0x448du
#define RX3R_CONTROL_BEAT_FX_TIME 0x448eu
#define RX3R_CONTROL_BEAT_FX_DEPTH 0x448fu
#define RX3R_CONTROL_BEAT_FX_PREVIOUS 0x4490u
#define RX3R_CONTROL_BEAT_FX_NEXT 0x4491u
#define RX3R_CONTROL_BEAT_FX_TAP 0x4492u
#define RX3R_CONTROL_MIXER_TRIM 0x5019u
#define RX3R_CONTROL_MIXER_EQ_HIGH 0x501au
#define RX3R_CONTROL_MIXER_EQ_MID 0x501bu
#define RX3R_CONTROL_MIXER_EQ_LOW 0x501cu
#define RX3R_CONTROL_MIXER_CHANNEL_FADER 0x501eu
#define RX3R_CONTROL_MIXER_INPUT_SOURCE 0x501fu
#define RX3R_CONTROL_MIXER_CUE 0x5020u
#define RX3R_CONTROL_SOUND_COLOR_FX_KNOB 0x509du
#define RX3R_CONTROL_SOUND_COLOR_FX_SPACE 0x50a1u
#define RX3R_CONTROL_SOUND_COLOR_FX_DUB_ECHO 0x50a2u
#define RX3R_CONTROL_SOUND_COLOR_FX_SWEEP 0x50a3u
#define RX3R_CONTROL_SOUND_COLOR_FX_NOISE 0x50a4u
#define RX3R_CONTROL_SOUND_COLOR_FX_CRUSH 0x50a5u
#define RX3R_CONTROL_SOUND_COLOR_FX_FILTER 0x50a6u
#define RX3R_CONTROL_SOUND_COLOR_FX_PARAMETER 0x50a7u
#define RX3R_CONTROL_MIXER_CROSSFADER 0x6017u
#define RX3R_CONTROL_MIXER_CROSSFADER_CURVE 0x6018u
#define RX3R_CONTROL_SYSTEM_POWER 0x8001u
#define RX3R_CONTROL_SYSTEM_USB_STOP 0x8002u

#endif
